export interface I_Game {
    id: number,
    img: string,
    name: string,
    plataforms: Array<string>,
    status: Array<string>,
    type: Array<string>,
    perspective: Array<string>,
    release: string,
    studio: string,
    achievements: Array<string>,
    ranked: string,
    languages: string,
    popularity: string,
    date: string,
    score: number,
    producers: Array<string>,
    recommendations: number,
    premiede: string,
    comments: number,
    description: string,
    choice: string,
    network: Array<string>,
    systemRequirements: Array<string>,
    time: string,
    themes: Array<string>,
    source: string
}
