export interface I_Game {
    id: number,
    gameImage: string,
    name: string,
    plataform: any,
    status: Array<string>,
    gameType: Array<string> | undefined,
    perspective: Array<string>,
    release: string,
    studio: any,
    achievements: any,
    ranked: string,
    languages: Array<string>,
    popularity: string,
    score: number,
    producer: any,
    recommendation: number,
    premiede: string,
    description: string,
    network: Array<string>,
    playTime: number,
    theme: any,
    source: string,
    imgs: any
}
