export interface I_Game {
    id: number,
    gameImage: string,
    name: string,
    plataforms: Array<string>,
    status: Array<string>,
    gameType: Array<string>,
    perspective: Array<string>,
    release: string,
    studios: Array<string>,
    achievements: Array<string>,
    ranked: string,
    languages: Array<string>,
    popularity: string,
    score: number,
    producers: Array<string>,
    recommendations: number,
    premiede: string,
    description: string,
    network: Array<string>,
    playTime: number,
    themes: Array<string>,
    source: string,
    img: Array<string>
}
