# Generated by Django 4.2.1 on 2023-10-04 18:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.DateField()),
                ('playtime', models.FloatField(default=0.0)),
                ('source', models.CharField(default='gameAPI', max_length=50)),
                ('premiede', models.CharField(default='unknow', max_length=30)),
                ('gameImage', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('langcod', models.CharField(max_length=10)),
                ('countrycod', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plataform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('userImage', models.CharField(max_length=550, null=True)),
                ('bornDate', models.DateField()),
                ('sexuality', models.CharField(choices=[('M', 'Masculine'), ('F', 'Female')], max_length=1)),
                ('joined', models.DateField(default=datetime.date.today)),
                ('note', models.CharField(blank=True, default='', max_length=550, null=True)),
                ('status', models.CharField(blank=True, default='off', max_length=50, null=True)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.auth')),
                ('friend', models.ManyToManyField(to='main.user')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.auth')),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(choices=[('3', 'Horrible'), ('5', 'Meh'), ('7', 'Fine'), ('8', 'Good'), ('9', 'Great'), ('10', 'Incredible')], max_length=30)),
                ('favorite', models.BooleanField(default=False)),
                ('recommendation', models.BooleanField(default=False)),
                ('progress', models.CharField(choices=[('Plan', 'Plan to Play'), ('Play', 'Playing'), ('Drop', 'Dropped'), ('Hold', 'On-Hold'), ('Replay', 'Replaying'), ('Complete', 'Completed')], default='Plan to Play', max_length=30)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='gameType',
            field=models.ManyToManyField(to='main.gametype'),
        ),
        migrations.AddField(
            model_name='game',
            name='language',
            field=models.ManyToManyField(to='main.language'),
        ),
        migrations.AddField(
            model_name='game',
            name='perspective',
            field=models.ManyToManyField(to='main.perspective'),
        ),
        migrations.AddField(
            model_name='game',
            name='plataform',
            field=models.ManyToManyField(to='main.plataform'),
        ),
        migrations.AddField(
            model_name='game',
            name='producer',
            field=models.ManyToManyField(to='main.producer'),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.ManyToManyField(to='main.status'),
        ),
        migrations.AddField(
            model_name='game',
            name='studio',
            field=models.ManyToManyField(to='main.studio'),
        ),
        migrations.AddField(
            model_name='game',
            name='theme',
            field=models.ManyToManyField(to='main.theme'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=300, null=True)),
                ('vote', models.CharField(blank=True, choices=[('0', 'Premiation'), ('1', 'Funny'), ('2', 'Yes'), ('3', 'No')], max_length=50, null=True)),
                ('publication', models.DateField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.AddField(
            model_name='auth',
            name='roles',
            field=models.ManyToManyField(to='main.role'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
            ],
        ),
    ]
