# Generated by Django 4.2.1 on 2023-10-04 18:09

from django.db import migrations
from main.management.commands.seeds import numberOfEntities

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            f'ALTER SEQUENCE main_auth_id_seq RESTART WITH {numberOfEntities + 1};'
            f'ALTER SEQUENCE main_user_id_seq RESTART WITH {numberOfEntities + 1};'
        )
    ]
