# Generated by Django 4.2.1 on 2023-10-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231004_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(null=True, to='main.user'),
        ),
    ]
