# Generated by Django 4.2.1 on 2023-10-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(to='main.user'),
        ),
    ]
