# Generated by Django 4.2.1 on 2023-08-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_joined_alter_user_note_alter_user_online'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Nationality',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='country',
            new_name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='online',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, default='off', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='note',
            field=models.CharField(blank=True, default='', max_length=550, null=True),
        ),
    ]
