# Generated by Django 4.2.1 on 2023-10-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_comment_publication_alter_comment_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='note',
            field=models.CharField(choices=[('3', 'Horrible'), ('5', 'Meh'), ('7', 'Fine'), ('8', 'Good'), ('9', 'Great'), ('10', 'Incredible')], max_length=30, null=True),
        ),
    ]
