# Generated by Django 4.2.1 on 2023-10-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_registry_note'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER SEQUENCE main_registry_id_seq RESTART WITH 46;'
        )
    ]
