# Generated by Django 4.2.1 on 2023-10-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_registry_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='progress',
            field=models.CharField(choices=[('Plan', 'Plan to Play'), ('Play', 'Playing'), ('Drop', 'Dropped'), ('Hold', 'On-Hold'), ('Replay', 'Replaying'), ('Complete', 'Completed')], default='Plan', max_length=30),
        ),
    ]
