# Generated by Django 4.2.1 on 2023-10-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_registry_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='vote',
            field=models.CharField(choices=[('PREMIATION', 'Premiation'), ('FUNNY', 'Funny'), ('YES', 'Yes'), ('NO', 'No')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registry',
            name='progress',
            field=models.CharField(choices=[('PLAN', 'Plan to Play'), ('PLAY', 'Playing'), ('DROP', 'Dropped'), ('HOLD', 'On-Hold'), ('REPLAY', 'Replaying'), ('COMPLETE', 'Completed')], default='PLAN', max_length=30),
        ),
    ]
