# Generated by Django 4.2.1 on 2023-10-18 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_comment_vote_alter_registry_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
