# Generated by Django 4.2.1 on 2023-10-18 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_registry_updatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
