# Generated by Django 4.2.1 on 2023-10-18 16:07

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_registry_updatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='updateDate',
            field=models.DateTimeField(blank=True, auto_now=True)
        ),
    ]
