# Generated by Django 4.2.1 on 2023-10-20 01:53

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_registry_updatedate'),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE EXTENSION IF NOT EXISTS pg_trgm;', reverse_sql=migrations.RunSQL.noop
        )
    ]
