# Generated by Django 4.2.1 on 2023-10-20 09:13

import datetime
import django.contrib.postgres.indexes
from django.db import migrations, models

from django.contrib.postgres.operations import BtreeGinExtension

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20231019_2253'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AlterField(
            model_name='registry',
            name='updateDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddIndex(
            model_name='game',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='NewGinIndex'),
        ),
    ]
