# Generated by Django 4.2.1 on 2023-10-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_registry_updatedate_game_newginindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='vote',
            field=models.CharField(choices=[(4, 'PREMIATION'), (3, 'FUNNY'), (1, 'YES'), (2, 'NO')], max_length=50, null=True),
        ),
    ]
