# Generated by Django 4.2.1 on 2023-12-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_comment_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='vote',
            field=models.CharField(choices=[(1, 'PREMIATION'), (2, 'FUNNY'), (3, 'YES'), (4, 'NO')], max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='registry',
            unique_together={('user', 'game')},
        ),
    ]
