# Generated by Django 4.2.1 on 2023-12-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_comment_vote_alter_registry_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publication',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
