# Generated by Django 4.2.1 on 2023-12-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_comment_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
