from main.subModels.img import Img
from main.subModels.role import Role
from main.subModels.auth import Auth
from main.subModels.link import Link
from main.subModels.user import User
from main.subModels.game import Game
from main.subModels.token import Token
from main.subModels.theme import Theme
from main.subModels.status import Status
from main.subModels.studio import Studio
from main.subModels.comment import Comment
from main.subModels.network import Network
from main.subModels.registry import Registry
from main.subModels.language import Language
from main.subModels.gametype import GameType
from main.subModels.producer import Producer
from main.subModels.plataform import Plataform
from main.subModels.perspective import Perspective
from main.subModels.nationality import Nationality
from main.subModels.achievement import Achievement