export const GAME_INITIAL_STATE: any = {
    id: 0,
    score: 0,
    name: "unknow",
    ranked: "",
    release: "unknow",
    premiede: "unknow",
    recommendation: 0,
    description: "Loading . . .",
    popularity: "unknow",
    playTime: 0.0,
    source: "unknow",
    status: ["unknow", "unknow"],
    network: ["unknow"],
    perspective: ["unknow"],
    languages: ["unknow", "unknow", "unknow"],
    gameType: undefined,
    plataform: [{value: undefined}],
    studio: [{value: undefined}],
    theme: [{value: undefined}],
    producer: [{value: undefined}],
    achievements: [{value: undefined}],
    gameImage: "https://img.freepik.com/fotos-premium/ilustracao-do-joystick-do-gamepad-do-controlador-de-jogos-cyberpunk_691560-5812.jpg",
    imgs: [
      {value: "https://img.freepik.com/fotos-premium/ilustracao-do-joystick-do-gamepad-do-controlador-de-jogos-cyberpunk_691560-5812.jpg"},
      {value: "https://img.freepik.com/fotos-premium/ilustracao-do-joystick-do-gamepad-do-controlador-de-jogos-cyberpunk_691560-5812.jpg"},
      {value: "https://img.freepik.com/fotos-premium/ilustracao-do-joystick-do-gamepad-do-controlador-de-jogos-cyberpunk_691560-5812.jpg"},
      {value: "https://img.freepik.com/fotos-premium/ilustracao-do-joystick-do-gamepad-do-controlador-de-jogos-cyberpunk_691560-5812.jpg"},
      {value: "https://img.freepik.com/fotos-premium/ilustracao-do-joystick-do-gamepad-do-controlador-de-jogos-cyberpunk_691560-5812.jpg"}
    ]
}